# Generated by Django 5.2.1 on 2025-09-27 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title for your ad", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of your item/service"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("property", "Property"),
                            ("vehicles", "Vehicles"),
                            ("electronics", "Electronics"),
                            ("furniture", "Furniture"),
                            ("clothing", "Clothing"),
                            ("services", "Services"),
                            ("jobs", "Jobs"),
                            ("education", "Education"),
                            ("pets", "Pets"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ad_type",
                    models.CharField(
                        choices=[
                            ("sell", "For Sale"),
                            ("buy", "Want to Buy"),
                            ("rent", "For Rent"),
                            ("service", "Service Offered"),
                            ("job", "Job Posting"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank if not applicable",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_phone", models.CharField(max_length=20)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "location",
                    models.CharField(help_text="City, State or Area", max_length=200),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Optional detailed address",
                        max_length=300,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True, help_text="e.g., New, Used, Like New", max_length=50
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, help_text="Brand name if applicable", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("views_count", models.IntegerField(default=0)),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertisement",
                "verbose_name_plural": "Advertisements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="ad_images/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("is_main", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ad.advertisement",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
